apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flask-app-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app-deploy
  template:
    metadata:
      labels:
        app: flask-app-deploy
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000