name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "flask-app/Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build docker image
        run: |
          cd flask-app
          docker build -t conjunrad/test_project:v${GITHUB_RUN_ID} . --push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Helm values
        run: |
          sed -i 's/\(tag:\).*/\1 v${GITHUB_RUN_ID}/' helm-chart/values.yaml
          git config user.name "GitHub CI"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update version of app"
          git push
